import type { Trip } from "@/types/trip"
import { hampiImages } from "@/constants/media"

export const trips: Trip[] = [
  {
    id: "hampi",
    slug: "hampi",
    destination: "Hampi",
    location: "Karnataka, India",
    coordinates: [15.335, 76.46],
    durationDays: 4,
    durationNights: 3,
    priceFrom: 24999,
    rating: 4.8,
    reviewCount: 312,
    tags: ["UNESCO Heritage", "Ruins", "Sunrise Point"],
    category: "Historical",
    shortDescription:
      "Wander the boulder-strewn ruins of a fallen empire, temple by temple.",
    description:
      "Once the capital of the Vijayanagara Empire, Hampi is a sprawling open-air museum of stone chariots, temple complexes, and boulder landscapes that turn gold at sunset. Walk through history without a single velvet rope.",
    highlights: [
      "Sunrise at Matanga Hill",
      "The Stone Chariot at Vittala Temple",
      "Sleeping Vishnu monolith",
      "Coracle ride on the Tungabhadra",
    ],
    thingsToDo: [
      "Cycle between temple ruins",
      "Watch the sunset from Hemakuta Hill",
      "Explore the Lotus Mahal and Elephant Stables",
      "Rock climbing on Hampi's boulders",
    ],
    bestTimeToVisit: "October to February",
    itinerary: [
      { day: 1, title: "Arrival & Hampi Bazaar", description: "Settle in, explore the Virupaksha Temple and riverside bazaar." },
      { day: 2, title: "Royal Enclosure", description: "Vittala Temple, Stone Chariot, and the Queen's Bath." },
      { day: 3, title: "Sunrise & Sacred Sites", description: "Matanga Hill sunrise, Sleeping Vishnu, coracle ride." },
      { day: 4, title: "Departure", description: "Leisure morning, local crafts shopping, departure." },
    ],
    faqs: [
      { question: "How do I get around Hampi?", answer: "Bicycles and mopeds are the easiest way to cover the ruins, which are spread over several kilometers." },
      { question: "Is Hampi family-friendly?", answer: "Yes, though some climbs (like Matanga Hill) involve uneven stone steps." },
    ],
    coverImage: hampiImages.stoneChariot,
    gallery: [
      hampiImages.stoneChariot,
      hampiImages.vishnuTemple,
      hampiImages.sleepingVishnu,
      hampiImages.matangaHillSunrise,
      hampiImages.stoneRuins,
    ],
  },
  {
    id: "udaipur",
    slug: "udaipur",
    destination: "Udaipur",
    location: "Rajasthan, India",
    coordinates: [24.5854, 73.7125],
    durationDays: 5,
    durationNights: 4,
    priceFrom: 38999,
    rating: 4.9,
    reviewCount: 508,
    tags: ["Luxury", "Lakes", "Palaces"],
    category: "Luxury",
    shortDescription: "The City of Lakes, where every rooftop faces a palace.",
    description:
      "Udaipur pairs Rajput grandeur with still, mirror-like lakes. Palace hotels, boat rides at dusk, and marble havelis make this one of India's most romantic heritage cities.",
    highlights: ["City Palace complex", "Lake Pichola boat ride", "Jagmandir Island Palace", "Sajjangarh Monsoon Palace at sunset"],
    thingsToDo: ["Sunset boat cruise on Lake Pichola", "Explore Saheliyon Ki Bari gardens", "Shop for miniature paintings in the old city", "Dine at a rooftop overlooking the lake"],
    bestTimeToVisit: "September to March",
    itinerary: [
      { day: 1, title: "Arrival & City Palace", description: "Check in, evening at the City Palace museum." },
      { day: 2, title: "Lake Pichola", description: "Boat ride to Jagmandir, old city walking tour." },
      { day: 3, title: "Monsoon Palace", description: "Sajjangarh sunset, local craft workshops." },
      { day: 4, title: "Day trip", description: "Kumbhalgarh Fort excursion." },
      { day: 5, title: "Departure", description: "Leisure morning, departure." },
    ],
    faqs: [{ question: "Is Udaipur good for a honeymoon?", answer: "Yes — it's consistently ranked among India's top romantic destinations." }],
    coverImage: hampiImages.sunsetPoint,
    gallery: [hampiImages.sunsetPoint, hampiImages.scenery1, hampiImages.karnatakaIndia1],
  },
  {
    id: "ranthambore",
    slug: "ranthambore",
    destination: "Ranthambore",
    location: "Rajasthan, India",
    coordinates: [26.0173, 76.5026],
    durationDays: 3,
    durationNights: 2,
    priceFrom: 21999,
    rating: 4.7,
    reviewCount: 189,
    tags: ["Wildlife", "Safari", "Tigers"],
    category: "Wildlife",
    shortDescription: "Track royal Bengal tigers through a ruined fortress jungle.",
    description:
      "Ranthambore National Park layers dramatic wildlife safaris over the ruins of a 10th-century fort — few places let you spot a tiger beneath a crumbling archway.",
    highlights: ["Tiger safari zones 1–5", "Ranthambore Fort", "Padam Talao lake", "Birdwatching at dawn"],
    thingsToDo: ["Two safari drives (dawn & dusk)", "Explore Ranthambore Fort", "Nature walks with a naturalist"],
    bestTimeToVisit: "October to April",
    itinerary: [
      { day: 1, title: "Arrival & evening safari", description: "Check in, first safari drive." },
      { day: 2, title: "Full day safaris", description: "Morning and evening safari, fort visit midday." },
      { day: 3, title: "Departure", description: "Final morning safari, departure." },
    ],
    faqs: [{ question: "Is a tiger sighting guaranteed?", answer: "No sighting is ever guaranteed in the wild, but Ranthambore has one of India's highest tiger-sighting rates." }],
    coverImage: hampiImages.scenery2,
    gallery: [hampiImages.scenery2, hampiImages.stoneRuins, hampiImages.karnataka1],
  },
  {
    id: "goa",
    slug: "goa",
    destination: "Goa",
    location: "Goa, India",
    coordinates: [15.2993, 74.124],
    durationDays: 4,
    durationNights: 3,
    priceFrom: 17999,
    rating: 4.6,
    reviewCount: 641,
    tags: ["Beaches", "Weekend Getaway", "Nightlife"],
    category: "Weekend Getaways",
    shortDescription: "Portuguese-tiled churches by day, beach shacks by night.",
    description:
      "Goa moves at two speeds: lazy mornings on the sand and lively nights along the coast. Spice plantations, old-world churches, and beach shacks round out the mix.",
    highlights: ["Basilica of Bom Jesus", "Anjuna flea market", "Sunset at Vagator beach", "Spice plantation tour"],
    thingsToDo: ["Beach hopping North to South Goa", "Sunset cruise on the Mandovi", "Water sports at Baga beach"],
    bestTimeToVisit: "November to February",
    itinerary: [
      { day: 1, title: "Arrival & North Goa", description: "Check in, evening at Baga beach." },
      { day: 2, title: "Old Goa churches", description: "Basilica of Bom Jesus, Se Cathedral, spice plantation." },
      { day: 3, title: "South Goa", description: "Palolem beach, sunset cruise." },
      { day: 4, title: "Departure", description: "Leisure morning, departure." },
    ],
    faqs: [{ question: "Which is better, North or South Goa?", answer: "North Goa is livelier and nightlife-focused; South Goa is quieter and more relaxed." }],
    coverImage: hampiImages.karnatakaIndia2,
    gallery: [hampiImages.karnatakaIndia2, hampiImages.beautifulArchitecture],
  },
  {
    id: "ladakh",
    slug: "ladakh",
    destination: "Ladakh",
    location: "Ladakh, India",
    coordinates: [34.1526, 77.5771],
    durationDays: 6,
    durationNights: 5,
    priceFrom: 42999,
    rating: 4.9,
    reviewCount: 276,
    tags: ["Adventure", "Mountains", "Road Trip"],
    category: "Adventure",
    shortDescription: "High-altitude passes, turquoise lakes, and Buddhist monasteries.",
    description:
      "Ladakh is stark, silent, and stunning — a high-desert landscape of Himalayan passes, cobalt lakes, and centuries-old monasteries perched on cliffs.",
    highlights: ["Pangong Tso lake", "Khardung La pass", "Thiksey Monastery", "Nubra Valley sand dunes"],
    thingsToDo: ["Road trip over Khardung La", "Camp beside Pangong Tso", "Monastery hopping", "Double-hump camel ride in Nubra"],
    bestTimeToVisit: "May to September",
    itinerary: [
      { day: 1, title: "Arrival & acclimatization", description: "Rest day in Leh to adjust to altitude." },
      { day: 2, title: "Leh monasteries", description: "Thiksey, Shey, and Hemis monasteries." },
      { day: 3, title: "Nubra Valley", description: "Cross Khardung La, camp in Nubra." },
      { day: 4, title: "Pangong Tso", description: "Drive to Pangong Tso, lakeside camping." },
      { day: 5, title: "Return to Leh", description: "Scenic drive back, local market visit." },
      { day: 6, title: "Departure", description: "Departure from Leh." },
    ],
    faqs: [{ question: "Do I need altitude acclimatization?", answer: "Yes, at least one full rest day in Leh before further travel is strongly recommended." }],
    coverImage: hampiImages.matangaHillSunrise,
    gallery: [hampiImages.matangaHillSunrise, hampiImages.sunset2022, hampiImages.scenery1],
  },
  {
    id: "kerala-backwaters",
    slug: "kerala-backwaters",
    destination: "Kerala Backwaters",
    location: "Alleppey, Kerala, India",
    coordinates: [9.4981, 76.3388],
    durationDays: 3,
    durationNights: 2,
    priceFrom: 19999,
    rating: 4.7,
    reviewCount: 355,
    tags: ["Houseboat", "Nature", "Relaxation"],
    category: "Luxury",
    shortDescription: "Drift through palm-lined canals aboard a private houseboat.",
    description:
      "A slow cruise through Kerala's backwaters on a traditional kettuvallam houseboat — coconut groves, paddy fields, and village life sliding gently past.",
    highlights: ["Overnight houseboat stay", "Vembanad Lake sunset", "Village canal tours", "Fresh Kerala seafood onboard"],
    thingsToDo: ["Houseboat cruise", "Ayurvedic massage", "Canoe through narrow canals", "Toddy shop visit"],
    bestTimeToVisit: "November to February",
    itinerary: [
      { day: 1, title: "Boarding & cruise", description: "Board the houseboat, afternoon cruise, sunset on Vembanad Lake." },
      { day: 2, title: "Village canals", description: "Canoe tour through narrow backwater villages." },
      { day: 3, title: "Departure", description: "Morning cruise back, disembark." },
    ],
    faqs: [{ question: "Is the houseboat private?", answer: "Yes, each booking is a private houseboat with its own crew and chef." }],
    coverImage: hampiImages.scenery1,
    gallery: [hampiImages.scenery1, hampiImages.karnatakaIndia3],
  },
  {
    id: "rishikesh",
    slug: "rishikesh",
    destination: "Rishikesh",
    location: "Uttarakhand, India",
    coordinates: [30.0869, 78.2676],
    durationDays: 3,
    durationNights: 2,
    priceFrom: 14999,
    rating: 4.6,
    reviewCount: 422,
    tags: ["Pilgrimage", "Yoga", "River Rafting"],
    category: "Pilgrimage",
    shortDescription: "The yoga capital of the world, on the banks of the Ganges.",
    description:
      "Rishikesh balances spiritual stillness with adrenaline — sunrise aartis on the ghats, ashrams and yoga schools, and white-water rafting on the Ganges.",
    highlights: ["Ganga Aarti at Triveni Ghat", "Laxman Jhula suspension bridge", "White-water rafting", "Beatles Ashram"],
    thingsToDo: ["Attend the evening Ganga Aarti", "White-water rafting on the Ganges", "Sunrise yoga session", "Explore the Beatles Ashram murals"],
    bestTimeToVisit: "September to April",
    itinerary: [
      { day: 1, title: "Arrival & Ganga Aarti", description: "Check in, evening aarti at Triveni Ghat." },
      { day: 2, title: "Rafting & ashrams", description: "Morning rafting, afternoon ashram visits." },
      { day: 3, title: "Departure", description: "Sunrise yoga, departure." },
    ],
    faqs: [{ question: "Is rafting safe for beginners?", answer: "Yes, guided rafting sessions include safety briefings and are suitable for first-timers." }],
    coverImage: hampiImages.karnatakaIndia3,
    gallery: [hampiImages.karnatakaIndia3, hampiImages.lotusTemple],
  },
  {
    id: "jaisalmer",
    slug: "jaisalmer",
    destination: "Jaisalmer",
    location: "Rajasthan, India",
    coordinates: [26.9157, 70.9083],
    durationDays: 4,
    durationNights: 3,
    priceFrom: 26999,
    rating: 4.8,
    reviewCount: 264,
    tags: ["Desert", "Road Trip", "Heritage"],
    category: "Road Trips",
    shortDescription: "A golden sandstone fort rising from the Thar desert.",
    description:
      "Jaisalmer's living fort, carved havelis, and sweeping dunes make it one of Rajasthan's most cinematic stops — best experienced at sunset, camel in tow.",
    highlights: ["Jaisalmer Fort at sunset", "Sam Sand Dunes", "Patwon Ki Haveli", "Desert camel safari"],
    thingsToDo: ["Camel safari into the Thar desert", "Explore the living fort's lanes", "Overnight desert camping", "Haveli architecture walk"],
    bestTimeToVisit: "October to March",
    itinerary: [
      { day: 1, title: "Arrival & fort", description: "Check in, explore Jaisalmer Fort at sunset." },
      { day: 2, title: "Havelis", description: "Patwon Ki Haveli, Nathmal Ki Haveli, local markets." },
      { day: 3, title: "Desert safari", description: "Drive to Sam Dunes, camel ride, overnight desert camp." },
      { day: 4, title: "Departure", description: "Return to city, departure." },
    ],
    faqs: [{ question: "How hot does it get in summer?", answer: "Summers (April–June) are extremely hot; the best window is October through March." }],
    coverImage: hampiImages.beautifulArchitecture,
    gallery: [hampiImages.beautifulArchitecture, hampiImages.stoneRuins, hampiImages.sunsetPoint],
  },
]

export function getTripBySlug(slug: string) {
  return trips.find((trip) => trip.slug === slug)
}

export function getRelatedTrips(trip: Trip, count = 3) {
  return trips.filter((t) => t.id !== trip.id && t.category === trip.category).slice(0, count)
    .concat(trips.filter((t) => t.id !== trip.id && t.category !== trip.category))
    .slice(0, count)
}
